In [27]:
import torch

x = torch.tensor([2.0], requires_grad=True)
y = x ** 2

# Detach the tensor 'x'
x_detached = x.detach()

# Calculate the Jacobian of 'y' with respect to 'x'
jac = torch.autograd.functional.jacobian(lambda x: y+x, x_detached)

print(jac)  # Output: None

tensor([[1.]])


In [11]:
def function(x):
    y = x.detach().numpy()
    z = y**2 + y*5
    return torch.tensor(z)

In [12]:
torch.autograd.functional.jacobian(function, torch.tensor([2.]))

tensor([[0.]])

In [32]:
def function(x):
    z = torch.tensor([0.], requires_grad=True)
    for i in range(5):
        z += 2*x
    return z

In [33]:
torch.autograd.functional.jacobian(function, torch.tensor([2.]))

RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

In [81]:
image= torch.zeros((39,2), dtype = torch.double)
avg_pose = torch.zeros(39*3, dtype = torch.double)

In [82]:
eigenposes = torch.ones((39*3,39*3), dtype = torch.double)
eigenvalues= torch.ones(39*3, dtype = torch.double)

In [96]:
def neg_log_density(pose2):
    pose = pose2.reshape((39,3))

    transform = torch.zeros((39,3))
    for i in range(39):
        transform[i][2] = 1

    pose = torch.squeeze(pose) + transform
    fx = 1.0
    fy = 1.0
    cx = 0
    cy = 0
    a1 = torch.tensor([[fx], [0], [cx]], dtype=torch.double)
    a2 = torch.tensor([[0], [fy], [cy]], dtype=torch.double)
    a3 = torch.tensor([[0],[0],[1]], dtype=torch.double)

    # Map the 3D point to 2D point
    p1 = pose@ a1
    p2 = pose @ a2
    p3 = pose @ a3

    projection = torch.hstack([p1/p3, p2/p3])

    n = projection - image
    #print(n)
    # note - taking the variance to be 1...
    pi = torch.tensor([0.], requires_grad=True)
    # for point in n:
    #     pi = pi+ torch.linalg.norm(point)**2 / 66.36
    #
    for i in range(len(eigenvalues)):
        pi = pi+ torch.dot(torch.tensor(eigenposes[i]),(torch.flatten(pose) -torch.tensor(avg_pose)))**2
    return pi

In [97]:
x = torch.ones((39*3), dtype = torch.double)*3

In [98]:
x

tensor([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3., 3., 3., 3., 3., 3.], dtype=torch.float64)

In [99]:
torch.autograd.functional.jacobian(neg_log_density, x)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_6744\2535238615.py:32: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  pi = pi+ torch.dot(torch.tensor(eigenposes[i]),(torch.flatten(pose) -torch.tensor(avg_pose)))**2


tensor([[91260., 91260., 91260., 91260., 91260., 91260., 91260., 91260., 91260.,
         91260., 91260., 91260., 91260., 91260., 91260., 91260., 91260., 91260.,
         91260., 91260., 91260., 91260., 91260., 91260., 91260., 91260., 91260.,
         91260., 91260., 91260., 91260., 91260., 91260., 91260., 91260., 91260.,
         91260., 91260., 91260., 91260., 91260., 91260., 91260., 91260., 91260.,
         91260., 91260., 91260., 91260., 91260., 91260., 91260., 91260., 91260.,
         91260., 91260., 91260., 91260., 91260., 91260., 91260., 91260., 91260.,
         91260., 91260., 91260., 91260., 91260., 91260., 91260., 91260., 91260.,
         91260., 91260., 91260., 91260., 91260., 91260., 91260., 91260., 91260.,
         91260., 91260., 91260., 91260., 91260., 91260., 91260., 91260., 91260.,
         91260., 91260., 91260., 91260., 91260., 91260., 91260., 91260., 91260.,
         91260., 91260., 91260., 91260., 91260., 91260., 91260., 91260., 91260.,
         91260., 91260., 912