In [3]:
import torch

In [92]:
def squared_cubed(x,y):
    return torch.stack([torch.linalg.norm(x),torch.linalg.norm(x), torch.linalg.norm(x)])

In [93]:
x = torch.tensor([0.,2.,1.,1.,1.])
y = torch.tensor([0.,1.,1.,0.,0.])

In [94]:
torch.autograd.functional.jacobian(squared_cubed,x,y).size()

RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [71]:
torch.stack([x,y]).size()

torch.Size([2, 5])

In [72]:
torch.autograd.functional.jacobian(squared_cubed).size()

TypeError: jacobian() missing 1 required positional argument: 'inputs'

In [83]:
# now, I need to get these jacobians.....
t = torch.autograd.functional.jacobian(squared_cubed,torch.stack([x,y]))

In [85]:
t.permute(1, 0, 2).size()

torch.Size([2, 3, 5])

In [87]:
import torch

# Create the tensor with size [4, 100, 57]
xs = torch.rand(4, 100, 57)

# Create the index tensor with size [4]
random_t = torch.tensor([1, 30, 50, 99])

# Use advanced indexing to select specific indices along the first and second dimensions
selected_xs = xs[:, random_t]

print(selected_xs.shape)  

torch.Size([4, 4, 57])


In [88]:
import torch

# Create batched and non-batched matrices
batch_size = 3
matrix_dim = 2
non_batched_matrix_dim = 2

# Create batched matrices of shape (batch_size, matrix_dim, matrix_dim)
batched_matrices = torch.randn(batch_size, matrix_dim, matrix_dim)

# Create a non-batched matrix of shape (non_batched_matrix_dim, non_batched_matrix_dim)
non_batched_matrix = torch.randn(non_batched_matrix_dim, non_batched_matrix_dim)

# Perform batch matrix multiplication using @ operator
result = batched_matrices @ non_batched_matrix

# Print the result
print("Batched Matrices:\n", batched_matrices)
print("\nNon-Batched Matrix:\n", non_batched_matrix)
print("\nResult:\n", result)

Batched Matrices:
 tensor([[[ 0.3398, -0.2226],
         [-1.0097,  0.5591]],

        [[ 0.6603,  0.1744],
         [ 0.4545,  2.6140]],

        [[-0.0354,  0.8737],
         [-0.4185,  0.3776]]])

Non-Batched Matrix:
 tensor([[ 0.8088, -0.2855],
        [-1.5518, -2.4587]])

Result:
 tensor([[[ 0.6202,  0.4503],
         [-1.6843, -1.0865]],

        [[ 0.2634, -0.6173],
         [-3.6887, -6.5567]],

        [[-1.3845, -2.1382],
         [-0.9244, -0.8090]]])


In [95]:
import torch

# Create a batched matrix of shape [4, 57, 4, 57]
batched_matrix = torch.randn(4, 57, 4, 57)

# Get the diagonal elements of the 57x57 matrices
diagonal_elements = batched_matrix[:, :, :, :].diagonal(dim1=-2, dim2=-1)

# Calculate the trace by summing the diagonal elements
traces = diagonal_elements.sum(-1)

# Print the traces
print("Traces:\n", traces)


Traces:
 tensor([[-3.8454e+00,  2.5049e+00,  2.2276e-01,  2.7254e+00, -1.4840e+00,
          5.7748e+00,  4.5237e-01,  3.3193e+00, -1.7595e+00, -3.0342e+00,
          3.1699e+00, -1.4665e+00, -6.3825e-02, -3.5255e+00,  4.3652e-01,
         -2.1836e+00, -5.0970e-01,  1.5395e+00, -2.9669e+00,  7.5835e-01,
          4.1624e+00, -3.7093e-01,  4.0884e-02,  2.3067e+00, -7.5649e-01,
          4.5448e-01, -1.3006e+00,  9.3706e-01,  1.1859e+00, -6.3099e-03,
         -3.4478e+00, -3.1067e+00, -1.9657e+00, -1.0239e-01, -4.0830e+00,
          2.3554e+00,  2.5788e-02,  1.1466e+00, -2.4826e+00,  1.5720e-02,
          4.7114e+00,  1.5419e+00, -1.0243e+00,  7.5275e-02,  5.6651e-01,
         -5.9050e-02,  2.4982e+00, -9.4654e-02,  2.7056e-02,  2.1597e+00,
         -1.5545e+00,  1.0912e+00,  1.3592e+00, -9.7059e-01,  2.8548e-01,
          1.9637e+00, -1.1709e+00],
        [-7.8619e-01,  2.2362e+00,  7.2102e-02, -2.2471e+00,  6.0517e-01,
         -2.5808e-01, -1.0299e+00, -1.2921e+00, -8.4105e-01, -1.172